const { chromium } = require("playwright")
;(async()=>{
  const b=await chromium.launch({headless:false,args:["--use-gl=angle","--use-angle=d3d11","--ignore-gpu-blocklist"]})
  const p=await (await b.newContext({viewport:{width:1440,height:900}})).newPage()
  await p.goto("https://crisp-hazel.vercel.app/map",{waitUntil:"domcontentloaded",timeout:60000})
  await p.waitForTimeout(6000)
  await p.click('button:has-text("Last 30 Days")'); await p.waitForTimeout(1200)
  await p.click('text=Custom Range'); await p.waitForTimeout(2000)
  const inputs=await p.$$eval("input",e=>e.map(x=>({type:x.type,ph:x.placeholder,id:x.id,name:x.name,val:x.value})))
  console.log("inputs:",JSON.stringify(inputs))
  const labels=await p.$$eval("label",e=>e.map(x=>x.innerText.trim()).filter(Boolean))
  console.log("labels:",JSON.stringify(labels.slice(0,10)))
  await b.close()
})()
